services:
  server-app:
    container_name: battery-devices-master-server
    image: battery-devices-master-server
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - path: ./.env
        required: true
    networks:
      - app-net
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./docs:/docs
    healthcheck:
      test: curl -f http://server-app:80/ping
      interval: 1s
      timeout: 1s
      retries: 30

  client-app:
    container_name: battery-devices-master-client
    image: battery-devices-master-client
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        SERVER_IP: server-app
    env_file:
      - path: ./.env
        required: true
    networks:
      - app-net
    ports:
      - ${CLIENT_PORT}:80
    depends_on:
      server-app:
        condition: service_healthy

networks:
  app-net:
