export enum InputType {
  color = 'color',
  date = 'date',
  datetime_local = 'datetime-local',
  email = 'email',
  month = 'month',
  number = 'number',
  integer = 'number',
  decimal = 'number',
  password = 'password',
  search = 'search',
  tel = 'tel',
  text = 'text',
  string = 'text',
  time = 'time',
  url = 'url',
  week = 'week',
}
