x-generator: NSwag v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Battery devices master
  description: API for battery devices master.
  contact:
    name: Sergey Morozov
    url: https://github.com/frostsergei
  version: v1
paths:
  /Ping:
    get:
      tags:
      - Ping
      summary: Check server health
      operationId: Ping_Ping
      responses:
        200:
          description: Server is healthy
  /api/Schema:
    get:
      tags:
      - Schema
      summary: Returns a schema that client needs to render
      operationId: Schema_Get
      parameters:
      - name: fileName
        in: query
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: Schema for a client
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/Schema/database:
    post:
      tags:
      - Schema
      summary: Writes the content of database JSON to XML file.
      operationId: Schema_Post
      requestBody:
        x-name: database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Database'
        required: true
        x-position: 1
      responses:
        200:
          description: Request message
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/Schema/parameters:
    post:
      tags:
      - Schema
      summary: Writes the content of a YAML string to a YAML file with configuration in the static directory.
      operationId: Schema_PostParameters
      requestBody:
        x-name: body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schema'
        required: true
        x-position: 1
      responses:
        200:
          description: Request message
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Unsuccessful file write
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/Schema/form:
    post:
      tags:
      - Schema
      summary: Writes the content of a YAML string to a YAML file with form in the static directory.
      operationId: Schema_PostForm
      requestBody:
        x-name: body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schema'
        required: true
        x-position: 1
      responses:
        200:
          description: Request message
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/Schema/dummy:
    get:
      tags:
      - Schema
      summary: Returns dummy schema
      operationId: Schema_GetJsonSchema
      responses:
        200:
          description: Dummy json schema
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
components:
  schemas:
    ErrorResponse:
      type: object
      description: "Error response with message"
      additionalProperties: false
      required:
      - message
      properties:
        message:
          type: string
          description: "Error message"
          minLength: 1
    Database:
      type: object
      description: "JSON form configuration request body"
      additionalProperties: false
      required:
      - content
      properties:
        content:
          type: string
          description: "Message with JSON form"
          minLength: 1
    Schema:
      type: object
      description: "Yaml configuration request body"
      additionalProperties: false
      required:
      - content
      properties:
        content:
          type: string
          description: "Yaml configuration message"
          minLength: 1
