x-generator: NSwag v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Battery devices master
  description: API for battery devices master.
  contact:
    name: Sergey Morozov
    url: https://github.com/frostsergei
  version: v1
paths:
  /api/Echo:
    post:
      tags:
      - Echo
      summary: Echo-server handler
      operationId: Echo_Echo
      requestBody:
        x-name: body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EchoBody'
        required: true
        x-position: 1
      responses:
        200:
          description: Request message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoBody'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /Ping:
    get:
      tags:
      - Ping
      summary: Check server health
      operationId: Ping_Ping
      responses:
        200:
          description: Server is healthy
components:
  schemas:
    EchoBody:
      type: object
      description: "Echo request/response body"
      additionalProperties: false
      required:
      - message
      properties:
        message:
          type: string
          description: "Echo message"
          minLength: 1
    ErrorResponse:
      type: object
      description: "Error response with message"
      additionalProperties: false
      required:
      - message
      properties:
        message:
          type: string
          description: "Error message"
          minLength: 1
