x-generator: NSwag v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Battery devices master
  description: API for battery devices master.
  contact:
    name: Sergey Morozov
    url: https://github.com/frostsergei
  version: v1
paths:
  /api/Echo:
    post:
      tags:
      - Echo
      summary: Echo-server handler
      operationId: Echo_Echo
      requestBody:
        x-name: body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextMessage'
        required: true
        x-position: 1
      responses:
        200:
          description: Request message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextMessage'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /Ping:
    get:
      tags:
      - Ping
      summary: Check server health
      operationId: Ping_Ping
      responses:
        200:
          description: Server is healthy
  /api/Yaml:
    post:
      tags:
      - Yaml
      summary: Writes the content of a YAML string to a YAML file in the static directory.
      operationId: Yaml_Post
      requestBody:
        x-name: body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/YamlConfigurationBody'
        required: true
        x-position: 1
      responses:
        200:
          description: Request message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextMessage'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Unsuccessful file write
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    TextMessage:
      type: object
      description: "Text message response body"
      additionalProperties: false
      required:
      - message
      properties:
        message:
          type: string
          description: "Text message"
          minLength: 1
    ErrorResponse:
      type: object
      description: "Error response with message"
      additionalProperties: false
      required:
      - message
      properties:
        message:
          type: string
          description: "Error message"
          minLength: 1
    YamlConfigurationBody:
      type: object
      description: "Yaml configuration request body"
      additionalProperties: false
      required:
      - yamlConfiguration
      properties:
        yamlConfiguration:
          type: string
          description: "Yaml configuration message"
          minLength: 1
