name: dotnet format

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.cs'

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format
        
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Run dotnet format
        run: dotnet format server.csproj --verify-no-changes