name: integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run integration tests
        run: docker compose up --build --exit-code-from test-app
        working-directory: ./integration_tests

