name: dotnet format

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.cs'

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore dotnet context
        run: dotnet restore
        working-directory: ./server

      - name: Run tests
        run: dotnet test
        working-directory: ./server

